# Import All Libraries I Need ....

In [1]:
# import our modules 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

### First let's import our dataset and take a look to it.

In [6]:
dataset = pd.read_csv('..\Car Emission Prediction\Car_Emission.csv',encoding='latin')
dataset

,Manufacturer,Model,Description,Transmission,Engine Capacity,Fuel Type,Electric energy consumption Miles/kWh,wh/km,Maximum range (Km),Maximum range (Miles),...,Emissions NOx [mg/km],THC + NOx Emissions [mg/km],Particulates [No.] [mg/km],Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,ALFA ROMEO,"MiTo Series 3, September 2016 Onwards",1.3 JTDm-2 95 bhp,M5,1248.0,Diesel,NaN,NaN,NaN,NaN,...,67.0,100.0,0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW,"1 Series 3-door F21, From September 2012",116d ED Plus 16'' tyres,M6,1496.0,Diesel,NaN,NaN,NaN,NaN,...,37.0,66.0,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMW,"1 Series 5-door F20, From September 2011",116d ED Plus 16'' tyres,M6,1496.0,Diesel,NaN,NaN,NaN,NaN,...,37.0,66.0,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CITROEN,C4,BlueHDi 100 S&S,M5,1560.0,Diesel,NaN,NaN,NaN,NaN,...,55.0,74.0,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CITROEN,C4 Cactus,BlueHDi 100 S&S ETG6,AMT6,1560.0,Diesel,NaN,NaN,NaN,NaN,...,40.0,53.0,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,LEXUS,LC MY2017,LC 500h Sport Pack,E-CVT,3456.0,Petrol Hybrid,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5114,LEXUS,LC MY2017,LC 500h Sport Plus Pack,E-CVT,3456.0,Petrol Hybrid,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5115,INFINITI,"Q50 Euro6, 2016",Q50S Hybrid AWD,A7,3498.0,Petrol Hybrid,NaN,NaN,NaN,NaN,...,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5116,LEXUS,"RC 200t, MY2015",F Sport,E-CVT,1998.0,Petrol Hybrid,NaN,NaN,NaN,NaN,...,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5117,LEXUS,"RC 200t, MY2015",Premier,E-CVT,1998.0,Petrol Hybrid,NaN,NaN,NaN,NaN,...,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## now we need to seperate the dependant and independent variables

In [92]:
features_matrix = dataset.drop(['Model','Euro Standard','Description','Fuel Cost 12000 Miles','Transmission'], axis=1)
features_matrix

,Manufacturer,Engine Capacity,Fuel Type,Electric energy consumption Miles/kWh,wh/km,Maximum range (Km),Maximum range (Miles),Metric Urban (Cold),Metric Extra-Urban,Metric Combined,...,Emissions NOx [mg/km],THC + NOx Emissions [mg/km],Particulates [No.] [mg/km],Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,ALFA ROMEO,1248.0,Diesel,NaN,NaN,NaN,NaN,4.3,2.9,3.4,...,67.0,100.0,0.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMW,1496.0,Diesel,NaN,NaN,NaN,NaN,3.9,3.1,3.4,...,37.0,66.0,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMW,1496.0,Diesel,NaN,NaN,NaN,NaN,3.9,3.1,3.4,...,37.0,66.0,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CITROEN,1560.0,Diesel,NaN,NaN,NaN,NaN,3.7,3.1,3.3,...,55.0,74.0,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CITROEN,1560.0,Diesel,NaN,NaN,NaN,NaN,3.9,3.2,3.4,...,40.0,53.0,0.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,LEXUS,3456.0,Petrol Hybrid,NaN,NaN,NaN,NaN,7.3,6.0,6.5,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5114,LEXUS,3456.0,Petrol Hybrid,NaN,NaN,NaN,NaN,7.3,6.0,6.5,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5115,INFINITI,3498.0,Petrol Hybrid,NaN,NaN,NaN,NaN,9.6,5.3,6.8,...,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5116,LEXUS,1998.0,Petrol Hybrid,NaN,NaN,NaN,NaN,9.6,5.9,7.3,...,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5117,LEXUS,1998.0,Petrol Hybrid,NaN,NaN,NaN,NaN,9.6,5.9,7.3,...,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Correlation Between Survived and anthor columns

In [93]:
goal_vector = dataset['Total cost / 12000 miles']
goal_vector

0         £807
1         £807
2         £807
3         £784
4         £807
         ...
5113    £1,505
5114    £1,505
5115    £1,577
5116    £1,692
5117    £1,692
Name: Total cost / 12000 miles, Length: 5118, dtype: object

## We can achieve the same result using pandas    null Values

In [94]:
print(features_matrix.isna().sum())

Manufacturer                                0
Engine Capacity                            30
Fuel Type                                   0
Electric energy consumption Miles/kWh    5037
wh/km                                    5037
Maximum range (Km)                       5037
Maximum range (Miles)                    5037
Metric Urban (Cold)                        81
Metric Extra-Urban                         81
Metric Combined                            30
Imperial Urban (Cold)                      81
Imperial Extra-Urban                       81
Imperial Combined                          30
CO2 g/km                                    0
Electricity cost                         5037
Total cost / 12000 miles                    0
Noise Level dB(A)                           0
Emissions CO [mg/km]                       30
THC Emissions [mg/km]                    2611
Emissions NOx [mg/km]                      30
THC + NOx Emissions [mg/km]              2536
Particulates [No.] [mg/km]               2529
Unnamed: 27                              5118
Unnamed: 28                              5118
Unnamed: 29                              5118
Unnamed: 30                              5118
Unnamed: 31                              5118
Unnamed: 32                              5118
Unnamed: 33                              5118
dtype: int64

## Handling the missing data
### we have two options : 
###    1. remove the Column

In [95]:
features_matrix = features_matrix.drop(['Electricity cost','Electric energy consumption Miles/kWh'
                                        ,'wh/km'                                    
                                        ,'Maximum range (Km)'                       
                                        ,'Maximum range (Miles)','Unnamed: 27','Unnamed: 28','Unnamed: 29','Unnamed: 30'
                                        ,'Unnamed: 31','Unnamed: 32','Unnamed: 33','Particulates [No.] [mg/km]','THC + NOx Emissions [mg/km]','THC Emissions [mg/km]'], axis=1)

features_matrix

,Manufacturer,Engine Capacity,Fuel Type,Metric Urban (Cold),Metric Extra-Urban,Metric Combined,Imperial Urban (Cold),Imperial Extra-Urban,Imperial Combined,CO2 g/km,Total cost / 12000 miles,Noise Level dB(A),Emissions CO [mg/km],Emissions NOx [mg/km]
0,ALFA ROMEO,1248.0,Diesel,4.3,2.9,3.4,65.7,97.4,83.1,89,£807,67.5,234.0,67.0
1,BMW,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89,£807,68.0,119.0,37.0
2,BMW,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89,£807,68.0,119.0,37.0
3,CITROEN,1560.0,Diesel,3.7,3.1,3.3,76.3,91.1,85.6,86,£784,68.8,272.0,55.0
4,CITROEN,1560.0,Diesel,3.9,3.2,3.4,72.4,88.3,83.1,89,£807,69.2,185.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,LEXUS,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148,"£1,505",67.0,283.0,5.0
5114,LEXUS,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148,"£1,505",67.0,283.0,5.0
5115,INFINITI,3498.0,Petrol Hybrid,9.6,5.3,6.8,29.4,53.3,41.5,159,"£1,577",69.0,207.0,27.0
5116,LEXUS,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168,"£1,692",70.0,278.0,58.0
5117,LEXUS,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168,"£1,692",70.0,278.0,58.0

In [96]:
features_matrix = features_matrix.drop(['Total cost / 12000 miles'],axis=1)

In [63]:
print(features_matrix.isna().sum())

Manufacturer              0
Transmission             32
Engine Capacity          30
Fuel Type                 0
Metric Urban (Cold)      81
Metric Extra-Urban       81
Metric Combined          30
Imperial Urban (Cold)    81
Imperial Extra-Urban     81
Imperial Combined        30
CO2 g/km                  0
Fuel Cost 12000 Miles    30
Noise Level dB(A)         0
Emissions CO [mg/km]     30
Emissions NOx [mg/km]    30
dtype: int64

###    2. replace it by the Mean (which is what we're going to do)

In [97]:
from sklearn.preprocessing import Imputer
# make a new imputer 
imputer = Imputer(missing_values='NaN', strategy='most_frequent',axis=0)
features_matrix[['Engine Capacity','Metric Urban (Cold)','Metric Extra-Urban','Metric Combined',
                 'Imperial Urban (Cold)','Imperial Extra-Urban','Imperial Urban (Cold)'    
                ,'Imperial Extra-Urban'   
                ,'Imperial Combined'    
                ,'CO2 g/km'         
                ,'Noise Level dB(A)'         
                ,'Emissions CO [mg/km]'     
                ,'Emissions NOx [mg/km]']] = imputer.fit_transform(features_matrix[['Engine Capacity','Metric Urban (Cold)','Metric Extra-Urban','Metric Combined','Imperial Urban (Cold)',
                                                                                                                         'Imperial Extra-Urban','Imperial Urban (Cold)'    
                                                                                        ,'Imperial Extra-Urban'   
                                                                                        ,'Imperial Combined'    
                                                                                        ,'CO2 g/km'       
                                                                                           
                                                                                        ,'Noise Level dB(A)'         
                                                                                        ,'Emissions CO [mg/km]'     
                                                                                        ,'Emissions NOx [mg/km]']])
features_matrix

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

,Manufacturer,Engine Capacity,Fuel Type,Metric Urban (Cold),Metric Extra-Urban,Metric Combined,Imperial Urban (Cold),Imperial Extra-Urban,Imperial Combined,CO2 g/km,Noise Level dB(A),Emissions CO [mg/km],Emissions NOx [mg/km]
0,ALFA ROMEO,1248.0,Diesel,4.3,2.9,3.4,65.7,97.4,83.1,89.0,67.5,234.0,67.0
1,BMW,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
2,BMW,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
3,CITROEN,1560.0,Diesel,3.7,3.1,3.3,76.3,91.1,85.6,86.0,68.8,272.0,55.0
4,CITROEN,1560.0,Diesel,3.9,3.2,3.4,72.4,88.3,83.1,89.0,69.2,185.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,LEXUS,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5114,LEXUS,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5115,INFINITI,3498.0,Petrol Hybrid,9.6,5.3,6.8,29.4,53.3,41.5,159.0,69.0,207.0,27.0
5116,LEXUS,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0
5117,LEXUS,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0

In [98]:
print(features_matrix.isna().sum())

Manufacturer             0
Engine Capacity          0
Fuel Type                0
Metric Urban (Cold)      0
Metric Extra-Urban       0
Metric Combined          0
Imperial Urban (Cold)    0
Imperial Extra-Urban     0
Imperial Combined        0
CO2 g/km                 0
Noise Level dB(A)        0
Emissions CO [mg/km]     0
Emissions NOx [mg/km]    0
dtype: int64

 ### 3. replace it by the Most Frequent (which is what we're going to do)

## Handling Categorical Data 
### models prefer to deal with numbers rather than words if possible, that's what we are going to do now 
## 1- "Manufacturer"

In [101]:
# import the needed librarys
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
features_matrix['Manufacturer'] = encoder.fit_transform(features_matrix['Manufacturer'])
features_matrix

,Manufacturer,Engine Capacity,Fuel Type,Metric Urban (Cold),Metric Extra-Urban,Metric Combined,Imperial Urban (Cold),Imperial Extra-Urban,Imperial Combined,CO2 g/km,Noise Level dB(A),Emissions CO [mg/km],Emissions NOx [mg/km]
0,1,1248.0,Diesel,4.3,2.9,3.4,65.7,97.4,83.1,89.0,67.5,234.0,67.0
1,5,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
2,5,1496.0,Diesel,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
3,8,1560.0,Diesel,3.7,3.1,3.3,76.3,91.1,85.6,86.0,68.8,272.0,55.0
4,8,1560.0,Diesel,3.9,3.2,3.4,72.4,88.3,83.1,89.0,69.2,185.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,21,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5114,21,3456.0,Petrol Hybrid,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5115,16,3498.0,Petrol Hybrid,9.6,5.3,6.8,29.4,53.3,41.5,159.0,69.0,207.0,27.0
5116,21,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0
5117,21,1998.0,Petrol Hybrid,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0

## Fuel Type

In [103]:
# import the needed librarys
features_matrix['Fuel Type'] = encoder.fit_transform(features_matrix['Fuel Type'])
features_matrix

,Manufacturer,Engine Capacity,Fuel Type,Metric Urban (Cold),Metric Extra-Urban,Metric Combined,Imperial Urban (Cold),Imperial Extra-Urban,Imperial Combined,CO2 g/km,Noise Level dB(A),Emissions CO [mg/km],Emissions NOx [mg/km]
0,1,1248.0,0,4.3,2.9,3.4,65.7,97.4,83.1,89.0,67.5,234.0,67.0
1,5,1496.0,0,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
2,5,1496.0,0,3.9,3.1,3.4,72.4,91.1,83.1,89.0,68.0,119.0,37.0
3,8,1560.0,0,3.7,3.1,3.3,76.3,91.1,85.6,86.0,68.8,272.0,55.0
4,8,1560.0,0,3.9,3.2,3.4,72.4,88.3,83.1,89.0,69.2,185.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5113,21,3456.0,7,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5114,21,3456.0,7,7.3,6.0,6.5,38.7,47.1,43.5,148.0,67.0,283.0,5.0
5115,16,3498.0,7,9.6,5.3,6.8,29.4,53.3,41.5,159.0,69.0,207.0,27.0
5116,21,1998.0,7,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0
5117,21,1998.0,7,9.6,5.9,7.3,29.4,47.9,38.7,168.0,70.0,278.0,58.0

In [106]:
goal_vector = encoder.fit_transform(goal_vector)
goal_vector

array([233, 233, 233, ...,  84,  97,  97], dtype=int64)

## a good way to handle such case, is to use the one hot encoder

### Now let's have our data encoded in a dummy variables, so we no longer have the problem of one country or(category) taking a higher value than the other

In [107]:
# import the oneHotEncoder class
from sklearn.preprocessing import OneHotEncoder
oneHotEncoder = OneHotEncoder(categorical_features=[3])
features_matrix = oneHotEncoder.fit_transform(features_matrix).toarray()
features_matrix[:, :3]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Now we need to split our data to train and test data ..

In [120]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_matrix, goal_vector, test_size=.3, random_state=0)
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Perdiction

In [121]:
print(mean_squared_error(y_train, model.predict(x_train)))
model.score(x_train, y_train)

2867.91876676838

0.6304663277485683

In [122]:
print(mean_squared_error(y_test, model.predict(x_test)))
model.score(x_test, y_test)

2682.8073087409275

0.6535346858298667